title: Señor Performo
logo: /assets/img/logo.png
description: Performance 4 all
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Contact
    url: /contact.html