title: Architect theme
description: Architect is a theme for GitHub Pages.
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
navbar:
  - title: Home
    url: /
  - title: Subpage 1
    url: /subpage1
  - title: Subpage 2
    url: /subpage2
