remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: SrPerf homepage
description: Bookmark this to keep an eye on my project updates!
twitter_username: SrPerf
github_username: SrPerf
navbar:
  - title: Home
    url: /
  - title: Subpage 1
    url: /subpage1
  - title: Subpage 2
    url: /subpage2
